name: Build and Push to Google Cloud run (Develop Enviroment)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set Github ENV variables
        id: SET_SKYPE_ID
        if: ${{ github.triggering_actor == 'skydark3004'}}
        run: |
          echo "github.triggering_actor: ${{ github.triggering_actor }}"
          echo "SKYPE_ID=live:.cid.34900d2be708c9d2" >> $GITHUB_OUTPUT
 
      - name: Create File Text
        run: |
          cat <<EOF > msg.txt
          ignore:
            # False positive, see https://github.com/anchore/grype/issues/558
            - vulnerability: CVE-2015-5237
              fix-state: unknown
              package:
                name: google.golang.org/protobuf
                version: v1.26.0
                type: go-module
                location: "/manager"
          EOF

      - name: Send skype
        uses: Eloco/docker-action-send-skype@v2
        with:
          skype_username: bots0000002@gmail.com
          skype_password: gony3004
          # Required skype_ids(both user_id  group_id) which u want to send to [also support multiple id which connect by space]
          skype_ids: ${{ steps.SET_SKYPE_ID.outputs.SKYPE_ID }}
          send_msg_path: msg.txt
