name: Build and Push to Google Cloud run (Develop Enviroment)

on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - 'main'
  push:
    branches:
      - 'main'
jobs:
  send_message_to_skype:
    runs-on: ubuntu-latest
    steps:
      - name: Export Variables
        id: EXPORT_VARIABLE
        shell: bash
        run: |
          echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "CURRENT_DATE=$(TZ=Asia/Ho_Chi_Minh date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          if [ "${{ github.triggering_actor }}" == "skydark30041" ]; then echo "SKYPE_ID=live:.cid.34900d2be708c9d2" >> $GITHUB_OUTPUT
          else
          echo "SKYPE_ID=NOT_FOUND" >> $GITHUB_OUTPUT
          fi

      - name: Create File Text
        if: ${{ steps.EXPORT_VARIABLE.outputs.SKYPE_ID != 'NOT_FOUND' }}
        run: |
          cat <<EOF > msg.txt
          - Branch: ${{ steps.EXPORT_VARIABLE.outputs.BRANCH }}
          - User: ${{ github.triggering_actor }}
          - Time: ${{ steps.EXPORT_VARIABLE.outputs.CURRENT_DATE }}
          - Repository: ${{ github.event.repository.name }}
          - Message: ${{ github.event.head_commit.message }}
          EOF

      - name: Send skype
        if: ${{ steps.EXPORT_VARIABLE.outputs.SKYPE_ID != 'NOT_FOUND' }}
        uses: Eloco/docker-action-send-skype@v2
        with:
          skype_username: bots0000002@gmail.com
          skype_password: gony3004
          # Required skype_ids(both user_id  group_id) which u want to send to [also support multiple id which connect by space]
          skype_ids: ${{ steps.EXPORT_VARIABLE.outputs.SKYPE_ID }}
          send_msg_path: msg.txt